import type { Sql } from 'postgres';

const animals = [
  {
    id: 1,
    firstName: 'Mochi',
    type: 'red panda',
    accessory: 'tiny yellow raincoat',
    birthDate: new Date('2021-04-17'),
  },
  {
    id: 2,
    firstName: 'Biscuit',
    type: 'capybara',
    accessory: 'striped bow tie',
    birthDate: new Date('2020-11-03'),
  },
  {
    id: 3,
    firstName: 'Pickle',
    type: 'otter',
    accessory: 'round sunglasses',
    birthDate: new Date('2022-07-28'),
  },
  {
    id: 4,
    firstName: 'Noodle',
    type: 'alpaca',
    accessory: 'sparkly wizard hat',
    birthDate: new Date('2019-02-14'),
  },
  {
    id: 5,
    firstName: 'Waffles',
    type: 'hedgehog',
    accessory: 'miniature backpack',
    birthDate: new Date('2023-09-09'),
  },
];

// // SafeQL errors on the sql(), but can be
// // configured with Postgres.js Plugin (Experimental)
// // - https://safeql.dev/compatibility/postgres.js.html
// await sql`
//   INSERT INTO
//     animals ${sql(animals, 'firstName', 'type', 'accessory', 'birthDate')}
// `;

export async function up(sql: Sql) {
  for (const animal of animals) {
    await sql`
      INSERT INTO
        animals (
          first_name,
          type,
          accessory,
          birth_date
        )
      VALUES
        (
          ${animal.firstName},
          ${animal.type},
          ${animal.accessory},
          ${animal.birthDate}
        )
    `;
  }
}

export async function down(sql: Sql) {
  for (const animal of animals) {
    // Technically leaky abstraction because id is
    // generated by the database so may not match
    // the JS data above
    await sql`
      DELETE FROM animals
      WHERE
        id = ${animal.id}
    `;
  }
}
