import GenerateButton from './GenerateButton';
import styles from './page.module.scss';

export const metadata = {
  title: 'my page title | Animals Anonymous',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <div>
      <h1>Animals for every occasion</h1>
      <GenerateButton />
      <div className={styles.dateString}>
        Current date ISO string: {new Date().toISOString()}
      </div>
    </div>
  );
}
