import Image from 'next/image';
import Link from 'next/link';
import catWithGlasses from '../public/images/cat-with-glasses.jpeg';
import AntipatternDocumentCookie from './AntipatternDocumentCookie';
import ClientComponentBrowserApis from './ClientComponentBrowserApis';
import GenerateButton from './GenerateButton';
import styles from './page.module.scss';

export const metadata = {
  title: 'my page title | Animals Anonymous',
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <div>
      <h1>Animals for every occasion</h1>
      <GenerateButton />
      <div className={styles.dateString}>
        Current date ISO string: {new Date().toISOString()}
      </div>
      <h2>Image using &lt;img&gt;</h2>
      <div>
        Best practice: hand-optimize the image first using something like
        https://squoosh.app/
      </div>
      <img
        src="/images/cat-with-glasses.jpeg"
        alt="cat with glasses"
        width={300}
      />
      <h2>Image using &lt;Image&gt; from next/image</h2>
      <div>
        Downside: This uses server capacity, which can cause slow page loads
      </div>
      <Image
        src="/images/cat-with-glasses.jpeg"
        alt="cat with glasses"
        // Option 1: Find dimensions of image and put them here
        width={300}
        height={300}
      />
      <Image
        // Option 2: Import the image and the size will be added by Next.js
        src={catWithGlasses}
        alt="cat with glasses"
        width={300}
      />
      <ClientComponentBrowserApis />
      <h2>Antipattern: Using document.cookie in a client component</h2>
      <AntipatternDocumentCookie />
      <h2>
        <Link href="/cookies-lang-switcher">Cookies Lang Switcher</Link>
      </h2>
      A better version of cookies
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
    </div>
  );
}
